
service: close-aws-account

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: prod
  region: us-east-1
  iam:
    role: 
      statements:
        - Effect: Allow
          Action:
            - organizations:*
          Resource:
            - '*'         

functions:
  close-aws-account:
    handler: close-aws-account.handler
